version: "3"
services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "lbd3_dev"
      # So you don't have to use root, but you can if you like
      MYSQL_USER: "lbd3"
      # You can use whatever password you like
      MYSQL_PASSWORD: "123qweXX"
      # Password for root access
      MYSQL_ROOT_PASSWORD: "123qweXX"
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
    networks:
      - my_net

  app:
    depends_on:
      - db
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
    networks:
      - my_net
    environment:
      SECRET_KEY: "123"
      DB_URI: "mysql://lbd3:123qweXX@db:3306/lbd3_dev"
      APP_IP: "127.0.0.1"
      APP_PORT: "5000"

networks:
  my_net:
    driver: bridge
