version: "3"
services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "lbd3_dev"
      MYSQL_USER: "lbd3"
      MYSQL_PASSWORD: "123qweXX"
      MYSQL_ROOT_PASSWORD: "123qweXX"
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
    networks:
      - my_net

  app:
    depends_on:
      - db
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
    networks:
      - my_net
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DB_URI: ${DB_URI}
      DEV_DB_URI: ${DEV_DB_URI}
      TEST_DB_URI: ${TEST_DB_URI}
      APP_IP: ${APP_IP}
      APP_PORT: ${APP_PORT}

networks:
  my_net:
    driver: bridge
